version: '3.8'

services:
  kubernetes:
    container_name: kubernetes
    tty: true
    build:
      context: .
    volumes:
      - '../company-versioning-api/.kubernetes/:/var/gke-utils'
      - './.gcloud/:/var/gcloud'
      - 'kube_data:/root/.kube'
      - 'docker_data:/root/.docker'
      - 'config_data:/root/.config'
      - 'cache_data:/root/.cache'

volumes:
  kube_data:
    driver: local
  docker_data:
    driver: local
  config_data:
    driver: local
  cache_data:
    driver: local
