version: '3.8'

# todo use service account credential to connect to the project (doc)

services:
  kubernetes:
    container_name: kubernetes
    tty: true
    build:
      context: .
      target: build
    volumes:
      - '../company-versioning-api/.kubernetes/:/var/charts/stack'
      - './.gcloud:/var/.gcloud'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'kube_data:/root/.kube'
      - 'docker_data:/root/.docker'
      - 'config_data:/root/.config'
      - 'cache_data:/root/.cache'

volumes:
  kube_data:
    driver: local
  docker_data:
    driver: local
  config_data:
    driver: local
  cache_data:
    driver: local
